### ISSUE TITLE
ImportError: no module named 'requests'

### ISSUE THREAD

**Issue by arxanas** [hfaran/piazza-api#27]
When trying to install `piazza-api` in an empty virtualenv, this error comes up:

```
$ virtualenv -p python3 .venv
$ source .venv/bin/activate
$ pip install piazza-api
Downloading/unpacking piazza-api
  Downloading piazza-api-0.5.0.tar.gz
  Running setup.py (path:/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/setup.py) egg_info for package piazza-api
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/setup.py", line 7, in <module>
        import piazza_api
      File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/__init__.py", line 1, in <module>
        from piazza_api.piazza import Piazza
      File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/piazza.py", line 1, in <module>
        from .rpc import PiazzaRPC
      File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/rpc.py", line 4, in <module>
        import requests
    ImportError: No module named 'requests'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/setup.py", line 7, in <module>

    import piazza_api

  File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/__init__.py", line 1, in <module>

    from piazza_api.piazza import Piazza

  File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/piazza.py", line 1, in <module>

    from .rpc import PiazzaRPC

  File "/Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api/piazza_api/rpc.py", line 4, in <module>

    import requests

ImportError: No module named 'requests'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Volumes/Home/Users/Waleed/tmp/python/piazza-api-test/.venv/build/piazza-api
Storing debug log for failure in /Users/Waleed/.pip/pip.log
```

The error is fixed by manually installing `requests` and then installing `piazza-api`. Do you know how to fix this issue? (Possibly by specifying a specific version of `requests` in `requirements.txt`?)

**Comment by hfaran** [comment]
So what happens here is `setup.py` imports `piazza_api` because it wants to get `piazza_api.__version__`. However, since I've recently updated the package so that you can `from piazza_api import Piazza` the import chain follows all the way through to `piazza_api.rpc`, a module which imports `requests` at the top-level.

This is one of those frustrating packaging issues to which there is no obviously great solution. In the past, I would have left `__init__.py` empty save for `__version__`, but I don't want to do that here. In this case, I think I'm going to copy the solution in the `setup.py` for `requests`: https://github.com/kennethreitz/requests/blob/master/setup.py#L31. It's not the most elegant, but honestly the best in my opinion.

**Comment by hfaran** [comment]
Thanks for catching this; I'll submit a PR with that fix.

**Comment by hfaran** [comment]
`0.5.1` has been published.
```
$ pip install piazza-api
Downloading/unpacking piazza-api
  Downloading piazza-api-0.5.1.tar.gz
  Running setup.py (path:/Users/hfaran/.virtualenv_Envs/piazza-api/build/piazza-api/setup.py) egg_info for package piazza-api
    
Downloading/unpacking requests (from piazza-api)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Installing collected packages: piazza-api, requests
  Running setup.py install for piazza-api
    
Successfully installed piazza-api requests
Cleaning up...
```

**Comment by arxanas** [comment]
That was quick, thanks :smile:
